/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_tdb2;

import java.nio.charset.StandardCharsets;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import redis.clients.jedis.util.Hashing;

/**
 *
 * @author angel
 */
public class Proyecto_TDB2 extends javax.swing.JFrame {

    /**
     * Creates new form Proyecto_TDB2
     */
    public Proyecto_TDB2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_registro = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jt_email = new javax.swing.JTextField();
        jt_nombres = new javax.swing.JTextField();
        jt_apellidos = new javax.swing.JTextField();
        jt_contra_registro = new javax.swing.JTextField();
        jt_fechaNacimiento = new javax.swing.JTextField();
        btn_registrar = new javax.swing.JButton();
        jd_publicaciones = new javax.swing.JDialog();
        cb_Personas = new javax.swing.JComboBox<>();
        cb_Publicacion = new javax.swing.JComboBox<>();
        b_Actualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_comentarios = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        b_CrearPublicacion = new javax.swing.JButton();
        jla_FotoPublicacion = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        b_FlechaDer = new javax.swing.JButton();
        b_FlechaIzq = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_perfil = new javax.swing.JMenuItem();
        MI_BuscarAmigos = new javax.swing.JMenuItem();
        jd_perfil = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jlabel_portada_perfil = new javax.swing.JLabel();
        jlabel_Nombre_perfil = new javax.swing.JLabel();
        jlabel_foto_perfil = new javax.swing.JLabel();
        jlabel_Apellido_perfil = new javax.swing.JLabel();
        jlabel_Email_perfil = new javax.swing.JLabel();
        jlabel_Edad_perfil = new javax.swing.JLabel();
        jb_edit_nombre = new javax.swing.JButton();
        jb_edit_apelllido = new javax.swing.JButton();
        jb_edit_email = new javax.swing.JButton();
        jb_edit_edad = new javax.swing.JButton();
        jb_edit_foto = new javax.swing.JButton();
        jb_edit_portada = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jt_email_login = new javax.swing.JTextField();
        jt_contra_login = new javax.swing.JTextField();
        btn_ingresar = new javax.swing.JButton();
        btn_registro = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Registro");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Email:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombres:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Apellidos:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Contraseña:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Fecha de Nacimiento:");

        btn_registrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_registrar.setText("Registrar");
        btn_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(151, 151, 151))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_email)
                            .addComponent(jt_nombres)
                            .addComponent(jt_apellidos)
                            .addComponent(jt_contra_registro)
                            .addComponent(jt_fechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jt_nombres, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jt_apellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jt_contra_registro, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jt_fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jd_registroLayout = new javax.swing.GroupLayout(jd_registro.getContentPane());
        jd_registro.getContentPane().setLayout(jd_registroLayout);
        jd_registroLayout.setHorizontalGroup(
            jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_registroLayout.setVerticalGroup(
            jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cb_Personas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cb_Publicacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        b_Actualizar.setText("Actualizar");
        b_Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_ActualizarMouseClicked(evt);
            }
        });

        jl_comentarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jl_comentarios);

        jLabel10.setText("Persona");

        jLabel11.setText("Publicacion");

        b_CrearPublicacion.setText("Crear Publicacion");
        b_CrearPublicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_CrearPublicacionMouseClicked(evt);
            }
        });

        jla_FotoPublicacion.setText("FOTO---------------------------------------------------------------------------------------------------------");

        jLabel13.setText("Comentarios");

        b_FlechaDer.setText("->");
        b_FlechaDer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_FlechaDerMouseClicked(evt);
            }
        });
        b_FlechaDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_FlechaDerActionPerformed(evt);
            }
        });

        b_FlechaIzq.setText("<-");
        b_FlechaIzq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_FlechaIzqMouseClicked(evt);
            }
        });

        jButton5.setText("jButton5");

        jMenu1.setText("Menu");

        jmi_perfil.setText("Ver perfil");
        jmi_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmi_perfilMouseClicked(evt);
            }
        });
        jMenu1.add(jmi_perfil);

        MI_BuscarAmigos.setText("Buscar Amigos");
        MI_BuscarAmigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MI_BuscarAmigosMouseClicked(evt);
            }
        });
        jMenu1.add(MI_BuscarAmigos);

        jMenuBar1.add(jMenu1);

        jd_publicaciones.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jd_publicacionesLayout = new javax.swing.GroupLayout(jd_publicaciones.getContentPane());
        jd_publicaciones.getContentPane().setLayout(jd_publicacionesLayout);
        jd_publicacionesLayout.setHorizontalGroup(
            jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_publicacionesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_publicacionesLayout.createSequentialGroup()
                        .addGroup(jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_Personas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(38, 38, 38)
                        .addGroup(jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jd_publicacionesLayout.createSequentialGroup()
                                .addComponent(cb_Publicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b_Actualizar)
                                .addGap(53, 53, 53)
                                .addComponent(b_CrearPublicacion))))
                    .addGroup(jd_publicacionesLayout.createSequentialGroup()
                        .addComponent(b_FlechaIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jla_FotoPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(b_FlechaDer, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_publicacionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
        jd_publicacionesLayout.setVerticalGroup(
            jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_publicacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_Personas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Publicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_Actualizar)
                    .addComponent(b_CrearPublicacion))
                .addGap(35, 35, 35)
                .addGroup(jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jla_FotoPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_FlechaDer)
                    .addComponent(b_FlechaIzq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jlabel_portada_perfil.setText("portada");
        jlabel_portada_perfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlabel_Nombre_perfil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabel_Nombre_perfil.setText("Nombre:");

        jlabel_foto_perfil.setText("foto");
        jlabel_foto_perfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlabel_Apellido_perfil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabel_Apellido_perfil.setText("Apellido:");

        jlabel_Email_perfil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabel_Email_perfil.setText("Email:");

        jlabel_Edad_perfil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabel_Edad_perfil.setText("Edad:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlabel_portada_perfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlabel_Email_perfil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlabel_Apellido_perfil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlabel_Nombre_perfil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                            .addComponent(jlabel_Edad_perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_edit_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_edit_apelllido, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_edit_email, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_edit_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jlabel_foto_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jb_edit_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                                .addComponent(jb_edit_portada, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabel_portada_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlabel_foto_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jb_edit_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jb_edit_portada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jb_edit_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlabel_Nombre_perfil))
                                        .addGap(18, 18, 18)
                                        .addComponent(jlabel_Apellido_perfil))
                                    .addComponent(jb_edit_apelllido, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jlabel_Email_perfil))
                            .addComponent(jb_edit_email, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jlabel_Edad_perfil))
                    .addComponent(jb_edit_edad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_perfilLayout = new javax.swing.GroupLayout(jd_perfil.getContentPane());
        jd_perfil.getContentPane().setLayout(jd_perfilLayout);
        jd_perfilLayout.setHorizontalGroup(
            jd_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_perfilLayout.setVerticalGroup(
            jd_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Login");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Email:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Contraseña:");

        btn_ingresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ingresar.setText("Ingresar");
        btn_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ingresarMouseClicked(evt);
            }
        });

        btn_registro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_registro.setText("Registrar");
        btn_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel7))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(77, 77, 77)
                            .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                            .addComponent(btn_registro))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jt_email_login)
                                .addComponent(jt_contra_login, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jt_email_login, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jt_contra_login, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ingresar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseClicked
        /*Creas la matiz 
          ej npmbre , valor en ma[0][0] ma[0][1]*/
        
        String[][] matriz = new String[5][2];
        matriz[0][0] = "Email";
        matriz[1][0] = "Nombre";
        matriz[2][0] = "Apellidos";
        matriz[3][0] = "Password";
        matriz[4][0] = "Date";
        
        matriz[0][1] = jt_email.getText();
        matriz[1][1] = jt_nombres.getText();
        matriz[2][1] = jt_apellidos.getText();
        matriz[3][1] = r.convertirSHA256(jt_contra_registro.getText());
        matriz[4][1] = jt_fechaNacimiento.getText();
        
        jt_email.setText("");
        jt_nombres.setText("");
        jt_apellidos.setText("");
        jt_contra_registro.setText("");
        jt_fechaNacimiento.setText("");
        
        if (!r.validarCorreo(matriz[0][1])) {
            r.Insertar_Registro("Cuenta:"+r.getNumerodeCuentas(),matriz);
            JOptionPane.showMessageDialog(this, "Cuenta creada");
        }else{
            JOptionPane.showMessageDialog(this, "Correo ya en uso, utilice otro");
        }
    }//GEN-LAST:event_btn_registrarMouseClicked

    private void btn_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registroMouseClicked
        jd_registro.setLocationRelativeTo(this);
        jd_registro.setVisible(true);
        jd_registro.pack();
    }//GEN-LAST:event_btn_registroMouseClicked

    private void btn_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarMouseClicked
        if (r.login(jt_email_login.getText(), jt_contra_login.getText()) != 0) {
            JOptionPane.showMessageDialog(this, "Cuenta encontrada");
            
            Map <String ,String> cuenta = r.Obtener_Registro("Cuenta:" + r.login(jt_email_login.getText(), jt_contra_login.getText()));
            cuentaActiva = new Cuenta(0, cuenta.values().toArray()[0].toString(), cuenta.values().toArray()[1].toString(), cuenta.values().toArray()[2].toString(), cuenta.values().toArray()[3].toString());
            System.out.println("Cuenta Activa" + cuentaActiva.toString());
            System.out.println(cuenta.values());
            cargarComboBox();
            jd_publicaciones.setLocationRelativeTo(this);
            jd_publicaciones.setVisible(true);
            jd_publicaciones.pack();
            
            
        }else{
            JOptionPane.showMessageDialog(this, "Cuenta no encontrada");
        }
    }//GEN-LAST:event_btn_ingresarMouseClicked

    private void jmi_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmi_perfilMouseClicked
        jd_perfil.setLocationRelativeTo(this);
        jd_perfil.setVisible(true);
        jd_perfil.pack();
    }//GEN-LAST:event_jmi_perfilMouseClicked

    private void b_FlechaDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_FlechaDerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_FlechaDerActionPerformed

    private void b_CrearPublicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_CrearPublicacionMouseClicked
        String[] contenido = new String[1];
        contenido[0] = "";
        contenido[1] = JOptionPane.showInputDialog("Que estas haciendo?");
        if (JOptionPane.showConfirmDialog(this, "Desea Agregar Imagen?") == 1) {
            //Agregar la foto url
        }
        Publicaciones publicacion = new Publicaciones(cuentaActiva.getId_cuenta(), 0, contenido, "20/11/2022");
    }//GEN-LAST:event_b_CrearPublicacionMouseClicked

    private void MI_BuscarAmigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MI_BuscarAmigosMouseClicked
        String nombreAmigo = JOptionPane.showInputDialog("Ingrese el nombre de una persona: ");
        if (true) {
            // ingresar validacion de si se encontro una persona
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró la persona");
        }
    }//GEN-LAST:event_MI_BuscarAmigosMouseClicked

    private void b_FlechaDerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_FlechaDerMouseClicked
        JOptionPane.showMessageDialog(this, "Pague $35 para el modo premium");
    }//GEN-LAST:event_b_FlechaDerMouseClicked

    private void b_FlechaIzqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_FlechaIzqMouseClicked
        JOptionPane.showMessageDialog(this, "Pague $35 para el modo premium");
    }//GEN-LAST:event_b_FlechaIzqMouseClicked

    private void b_ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_ActualizarMouseClicked
        //Actualizar Publicaciones
        //Por ahora solo texto
        String publica = cuentaActiva.getAmigos().get(cb_Personas.getSelectedIndex()).getNombre() + ": " +
                cuentaActiva.getAmigos().get(cb_Personas.getSelectedIndex()).getPublicaciones().get(cb_Publicacion.getSelectedIndex()).toString();
        jla_FotoPublicacion.setText(publica);
        //Actualizar Comentarios
        DefaultListModel<String> model = new DefaultListModel<>();

        for (int i = 0; i < cuentaActiva.getPublicaciones().size()-1; i++) {
            String comentario = "";
            for (int j = 0; j < cuentaActiva.getPublicaciones().get(i).getComentarios().size()-1; j++) {
                comentario =  cuentaActiva.getPublicaciones().get(i).getComentarios().get(j).getNombreComment() + cuentaActiva.getPublicaciones().get(i).getComentarios().get(j).getContenido() ;
            }
            model.addElement(comentario);
           
        }
        jl_comentarios.setModel(model);
    }//GEN-LAST:event_b_ActualizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyecto_TDB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyecto_TDB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyecto_TDB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyecto_TDB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proyecto_TDB2().setVisible(true);
            }
        });
    }
    
    public void cargarComboBox(){
        DefaultComboBoxModel<String> personas = new DefaultComboBoxModel<>();
        DefaultComboBoxModel<String> publicaciones = new DefaultComboBoxModel<>();
        for (int i = 0; i < cuentaActiva.getAmigos().size()-1; i++) {
            personas.addElement(cuentaActiva.getAmigos().get(i).getNombre());
            for (int j = 0; j < cuentaActiva.getAmigos().get(i).getPublicaciones().size(); j++) {
                //por ahora solo se imprime el texto, no la foto
                publicaciones.addElement(cuentaActiva.getAmigos().get(i).getPublicaciones().get(j).toString());
            }
        }
        
        cb_Personas.setModel(personas);
        cb_Publicacion.setModel(publicaciones);
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MI_BuscarAmigos;
    private javax.swing.JButton b_Actualizar;
    private javax.swing.JButton b_CrearPublicacion;
    private javax.swing.JButton b_FlechaDer;
    private javax.swing.JButton b_FlechaIzq;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JButton btn_registro;
    private javax.swing.JComboBox<String> cb_Personas;
    private javax.swing.JComboBox<String> cb_Publicacion;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_edit_apelllido;
    private javax.swing.JButton jb_edit_edad;
    private javax.swing.JButton jb_edit_email;
    private javax.swing.JButton jb_edit_foto;
    private javax.swing.JButton jb_edit_nombre;
    private javax.swing.JButton jb_edit_portada;
    private javax.swing.JDialog jd_perfil;
    private javax.swing.JDialog jd_publicaciones;
    private javax.swing.JDialog jd_registro;
    private javax.swing.JList<String> jl_comentarios;
    private javax.swing.JLabel jla_FotoPublicacion;
    private javax.swing.JLabel jlabel_Apellido_perfil;
    private javax.swing.JLabel jlabel_Edad_perfil;
    private javax.swing.JLabel jlabel_Email_perfil;
    private javax.swing.JLabel jlabel_Nombre_perfil;
    private javax.swing.JLabel jlabel_foto_perfil;
    private javax.swing.JLabel jlabel_portada_perfil;
    private javax.swing.JMenuItem jmi_perfil;
    private javax.swing.JTextField jt_apellidos;
    private javax.swing.JTextField jt_contra_login;
    private javax.swing.JTextField jt_contra_registro;
    private javax.swing.JTextField jt_email;
    private javax.swing.JTextField jt_email_login;
    private javax.swing.JTextField jt_fechaNacimiento;
    private javax.swing.JTextField jt_nombres;
    // End of variables declaration//GEN-END:variables
RedisConfig r = new RedisConfig();
Cuenta cuentaActiva;
}
